# Generated by Django 3.0.7 on 2021-06-29 10:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_add_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creative_skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('3D_Art', '3D Art'), ('3D_Modeling', '3D Modeling'), ('3D_Motion', '3D Motion')], default='Graphics', max_length=28),
        ),
    ]
