# Generated by Django 3.0.7 on 2021-06-29 11:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_creative_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='add_category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='creative_skills',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('All', 'All'), ('Novel', 'Novel'), ('10+1', '10+1'), ('10+2', '10+2'), ('10th', '10th'), ('B.Arch', 'B.Arch'), ('B.Com', 'B.Com'), ('B.Des', 'B.Des'), ('B.Ed', 'B.Ed'), ('B.Lib.Sc', 'B.Lib.Sc'), ('B.Pharmacy', 'B.Pharmacy'), ('B.Sc', 'B.Sc'), ('B.Sc Agriculture', 'B.Sc Agriculture'), ('B.Tech', 'B.Tech'), ('B.V.Sc', 'B.V.Sc'), ('BA', 'BA'), ('BAMS', 'BAMS'), ('BBA', 'BBA'), ('BCA', 'BCA'), ('BDS', 'BDS'), ('BFA', 'BFA'), ('BHMS', 'BHMS'), ('BMC', 'BMC'), ('BPEd', 'BPEd'), ('BPT', 'BPT'), ('BSW', 'BSW'), ('DM', 'DM'), ('LLB', 'LLB'), ('LLM', 'LLM'), ('M.Arch', 'M.Arch'), ('M.Ch', 'M.Ch'), ('M.Com', 'M.Com'), ('M.Design', 'M.Design'), ('M.Ed', 'M.Ed'), ('M.Lib.Sc', 'M.Lib.Sc'), ('M.Pharm', 'M.Pharm'), ('M.Phil', 'M.Phil'), ('M.Sc', 'M.Sc'), ('M.Sc Agriculture', 'M.Sc Agriculture'), ('M.Tech', 'M.Tech'), ('M.V.Sc', 'M.V.Sc'), ('MA', 'MA'), ('MBA', 'MBA'), ('MBBS', 'MBBS'), ('MCA', 'MCA'), ('MD', 'MD'), ('MDS', 'MDS'), ('MFA', 'MFA'), ('MMC / MMM', 'MMC / MMM'), ('MPT', 'MPT'), ('MS', 'MS'), ('MSW / MA (SW)', 'MSW / MA (SW)'), ('Nursing', 'Nursing'), ('Pharm.D', 'Pharm.D'), ('PhD', 'PhD'), ('Physical Education', 'Physical Education')], default='All', max_length=350),
        ),
    ]
