# Generated by Django 3.0.7 on 2021-07-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20210630_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parcel',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
