# Generated by Django 3.0.7 on 2021-07-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20210703_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
