# Generated by Django 3.0.7 on 2021-07-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feedback',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='suggestions',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
