# Generated by Django 3.0.7 on 2021-07-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20210704_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feedback',
            field=models.CharField(blank=True, default='None', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='suggestions',
            field=models.CharField(blank=True, default='None', max_length=150),
        ),
    ]
