# Generated by Django 3.0.7 on 2021-06-12 15:19

import authy.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=80, null=True)),
                ('profile_info', models.TextField(blank=True, max_length=1500, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=authy.models.user_directory_path, verbose_name='Picture')),
                ('occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=80, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=80, null=True)),
                ('youtube_url', models.CharField(blank=True, max_length=80, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=80, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=80, null=True)),
                ('favorites', models.ManyToManyField(to='post.Post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
