# Generated by Django 3.0.7 on 2021-06-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='youtube_url',
        ),
    ]
