# Generated by Django 3.0.7 on 2021-07-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_auto_20210623_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
